seed: 42

batch_size: 4096
num_epochs: 1000
validation_split: 0.8

experiment_name: "default"

lr: 1e-3

dataset:
  _target_: deep_tube_learning.datasets.ScalarTubeDataset.from_wandb
  wandb_experiment: "single_integrator_6u8wikhv"

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: ${lr}

lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  _partial_: true
  step_size: 10000
  gamma: 0.1

model:
  _target_: deep_tube_learning.models.MLP
  _partial_: true
  num_units: 32
  num_layers: 2
  activation:
    _target_: torch.nn.ReLU

loss:
  _target_: deep_tube_learning.losses.ScalarTubeLoss

steps_per_model_checkpoint: 100
steps_per_model_evaluation: 100

model_evaluation:
  _target_: deep_tube_learning.utils.evaluate_scalar_tube
  _partial_: true
