defaults:
  - default
  - _self_

experiment_name: "error_dynamics"

dataset:
  _target_: deep_tube_learning.datasets.ErrorDynamicsDataset.from_wandb
  wandb_experiment: "single_integrator_6u8wikhv"

loss:
  _target_: deep_tube_learning.losses.ErrorLoss

lr_scheduler:
  step_size: 1000
  gamma: 0.75

model:
  num_units: 32
  num_layers: 3

model_evaluation:
  _target_: deep_tube_learning.utils.evaluate_error_dynamics
  _partial_: true
