defaults:
  - default
  - _self_

num_epochs: 1000
experiment_name: "deep_tube_learning"

dataset:
  _target_: deep_tube_learning.datasets.ScalarHorizonTubeDataset.from_wandb
  wandb_experiment: "hopper_trajectory_single_int_r7v58tj0"
  H_fwd: 50
  H_rev: 25
loss:
  _target_: deep_tube_learning.losses.VectorTubeLoss
  alpha: 0.9

lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  _partial_: true
  step_size: 1000
  gamma: 0.75

model:
  _target_: deep_tube_learning.models.MLP
  _partial_: true
  num_units: 128
  num_layers: 2
  activation:
    _target_: torch.nn.Softplus
    beta: 5

model_evaluation:
  _target_: deep_tube_learning.utils.evaluate_scalar_tube_oneshot
  _partial_: true