defaults:
  - default
  - _self_

experiment_name: "deep_tube_learning"

loss:
  _target_: deep_tube_learning.losses.ScalarTubeLoss
  alpha: 0.8

lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  _partial_: true
  step_size: 2000
  gamma: 0.1