defaults:
  - default_custom
  - _self_

epochs: 2
train_epochs: 2
learning_iters: 50
p_cbf_horizon_s: 5
delta_max: 5
delta_K : 0.5
decorr_prop: 0.1
batch_size: 2048
steps_per_model_checkpoint: 1000

experiment_name: "double_single_int"
upload_to_wandb: False

controller:
  _target_: predictive_cbfs.controllers.DoubleSingleVelTracking
  k_d: 1
  robustified_cbf:
    _target_: predictive_cbfs.controllers.RobustifiedCBF
    cbf:
      _target_: predictive_cbfs.cbfs.ZeroCBF
      alpha: 5
      epsilon: 0
    nom_controller:
      _target_: predictive_cbfs.controllers.SingleIntConstVel
      v: -5.
    delta:
      _target_: deep_tube_learning.models.MLP
      input_size: 2
      output_dim: 1
      num_units: 64
      num_layers: 2
      activation:
        _target_: torch.nn.ReLU
#      final_activation:
#        _target_: torch.nn.ReLU
    dyn:
      _target_: predictive_cbfs.roms.SingleInt1D
      dt: 0.01


env_config:
  env:
    num_envs: 4096
    episode_length_s: 10
    model:
      dt: 0.01
      cls: 'DoubleInt1D'
  init_state:
    default_noise_lower: [ -0., -1. ]  # [foot, wheel1, 2, 3]
    default_noise_upper: [ 1., 1. ]

lr: 1e-2
lr_scheduler:
  _target_: "torch.optim.lr_scheduler.LambdaLR"
  _partial_: True
  lr_lambda:
    _target_: "deep_tube_learning.utils.get_warmup_cosine_decay"
    warmup_steps: 50
    max_steps: 400

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: ${lr}

loss_fn:
  _target_: predictive_cbfs.losses.CheckLoss
  alpha: 0.5

#loss_fn:
#  _target_: torch.nn.MSELoss  # predictive_cbfs.losses.SquaredLoss

eval_function:
  _target_: predictive_cbfs.eval_functions.evaluate_single_double_easy
  _partial_: True