seed: 42
steps_per_model_checkpoint: 10

acc_max: 1.0
acc_min: -1.0
alpha_max: 2.0
alpha_min: -2.0
vel_max: 0.35
vel_min: -0.35
vel_par_max: 1.0
vel_perp_max: 0.5
vel_par_min: -0.5
vel_perp_min: -0.5
omega_max: 1.0
omega_min: -1.0
pos_max: 1e9
pos_min: -1e9