seed: 42


task: 'hopper_flat_trajectory'
experiment_name: 'hopper_traj_single_int'

env_config:
  env:
    type: 'isaacgym'
    num_envs: 4096
    num_observations: 20
    num_actions: 4
    episode_length_s: 20
  rewards:
    scales:
      termination: -0.5
      ang_vel_xy: -0.05
      orientation: -1.0
      torques: -0.00001
      dof_vel: -0.
      dof_acc: -2.5e-7
      collision: -1.
      action_rate: -0.1
    only_positive_rewards: False  # if true negative total rewards are clipped at zero (avoids early termination problems)
    soft_dof_pos_limit: 1.  # percentage of urdf limits, values above this limit are penalized
    soft_dof_vel_limit: 1.
    soft_torque_limit: 1.
    base_height_target: .55
    max_contact_force: 100.  # forces above this value are penalized

  normalization:
    obs_scales:
      trajectory: [1, 1]

train_config:
  policy:
    actor_hidden_dims: [128, 64, 32]
    critic_hidden_dims: [128, 64, 32]
    activation: 'elu'
  algorithm:
    entropy_coef: 0.01
  runner:
    run_name: ''
    experiment_name: ${experiment_name}
    load_run: -1
    max_iterations: 400
