wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.12
    cli_version: 0.17.3
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1720036396
    t:
      1:
      - 1
      - 55
      - 105
      2:
      - 1
      - 55
      - 105
      3:
      - 2
      - 23
      - 37
      4: 3.9.12
      5: 0.17.3
      8:
      - 1
      - 5
      13: darwin-x86_64
alpha:
  desc: null
  value: 0.9
learning_rate:
  desc: null
  value: 0.001
num_epochs:
  desc: null
  value: 500
num_layers:
  desc: null
  value: 2
num_units:
  desc: null
  value: 32
tube_type:
  desc: null
  value: rectangular
