seed: 0

experiment_name: "hopper_single_int"

epochs: 10
train_epochs: 1
learning_iters: 50
p_cbf_horizon_s: 5
delta_max: 5
delta_K : 2
decorr_prop: 0.1
batch_size: 2048
steps_per_model_checkpoint: 100

controller: null

env_config:
  env:
    type: 'isaacgym'
    num_envs: 4096
    episode_length_s: 15
#  terrain:
#    curriculum: False
  noise:
    add_noise: False
  domain_rand:
    randomize_friction: False
    randomize_base_mass: False
    randomize_inv_base_mass: False
    push_robots: False
    rigid_shape_properties:
      randomize_restitution: False
      randomize_compliance: False
      randomize_thickness: False
    dof_properties:
      randomize_stiffness: False
      randomize_damping: False
    spring_properties:
      randomize_stiffness: False
      randomize_damping: False
      randomize_setpoint: False
    pd_gain_properties:
      randomize_p_gain: False
      randomize_d_gain: False
    torque_speed_properties:
      randomize_max_torque: False
      randomize_max_speed: False
      randomize_slope: False
  init_state:
    default_dof_pos_noise_lower: [ -0., -0., -0., -0. ]  # [foot, wheel1, 2, 3]
    default_dof_pos_noise_upper: [ 0., 0., 0., 0. ]
    default_dof_vel_noise_lower: [ -0., -0., -0., -0. ]
    default_dof_vel_noise_upper: [ 0., 0., 0., 0. ]
    default_root_pos_noise_lower: [ -3.0, -0.5, -0.0, -0.0, -0.0, -0.0, -0.0 ]  # [x, y, z, qx, qy, qz, qw]
    default_root_pos_noise_upper: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]
    default_root_vel_noise_lower: [ -0.0, -0.0, -0.0, -0.0, -0.0, -0.0 ]  # [vx, vy, vz, wx, wy, wz]
    default_root_vel_noise_upper: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]


lr: 1e-2
lr_scheduler:
  _target_: "torch.optim.lr_scheduler.LambdaLR"
  _partial_: True
  lr_lambda:
    _target_: "deep_tube_learning.utils.get_warmup_cosine_decay"
    warmup_steps: 250
    max_steps: 2000

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: ${lr}

loss_fn:
  _target_: predictive_cbfs.losses.CheckLoss
  alpha: 0.5

eval_function: null