seed: 0

experiment_name: "custom"

epochs: 10
train_epochs: 1
learning_iters: 50
p_cbf_horizon_s: 5
delta_max: 5
delta_K : 0.5
decorr_prop: 0.1
batch_size: 2048
steps_per_model_checkpoint: 100

controller: null

env_config:
  env:
    type: 'custom'
    num_envs: 8192
    episode_length_s: 20
    model:
  noise:
    add_noise: False
  domain_rand:
  init_state:
    default_noise_lower: [ -0., -0., -0., -0. ]  # [foot, wheel1, 2, 3]
    default_noise_upper: [ 0., 0., 0., 0. ]


lr: 1e-2
lr_scheduler:
  _target_: "torch.optim.lr_scheduler.LambdaLR"
  _partial_: True
  lr_lambda:
    _target_: "deep_tube_learning.utils.get_warmup_cosine_decay"
    warmup_steps: 250
    max_steps: 2000

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: ${lr}

loss_fn:
  _target_: predictive_cbfs.losses.CheckLoss
  alpha: 0.5

eval_function: null