defaults:
  - default_custom
  - _self_

experiment_name: "double_single_int"

epochs: 6
train_epochs: 1
learning_iters: 200
p_cbf_horizon_s: 5
delta_K : 0.5
decorr_prop: 0.1
batch_size: 2048
steps_per_model_checkpoint: 100
save_eval_data: True
save_training_data: False

adjust_distribution: True
converged_tol: 0.01
max_converged_proportion: 0.02

use_barrier: True
JPi_f_inds: [1]

controller:
  _target_: predictive_cbfs.controllers.DoubleSingleVelTracking
  k_d: 1
  robustified_cbf:
    _target_: predictive_cbfs.controllers.RobustifiedCBF
    cbf:
      _target_: predictive_cbfs.cbfs.ZeroCBF
      alpha: 5
      epsilon: 0
    nom_controller:
      _target_: predictive_cbfs.controllers.SingleIntConstVel
      v: -5.
    delta:
      _target_: deep_tube_learning.models.MLP
      input_size: 2
      output_dim: 1
      num_units: 64
      num_layers: 2
      activation:
        _target_: torch.nn.ReLU
    dyn:
      _target_: predictive_cbfs.roms.SingleInt1D
      dt: 0.01
    delta_max: 5


env_config:
  env:
    num_envs: 4096
    episode_length_s: 6
    dt: 0.01
    model:
      dt: ${env_config.env.dt}
      cls: 'DoubleInt1D'
  init_state:
    default_noise_lower: [ -0., -1. ]  # [foot, wheel1, 2, 3]
    default_noise_upper: [ 1., 1. ]

eta_schedule:
  _target_: predictive_cbfs.utils.eta_schedule
  _partial_: True
  eta_max: ${delta_K}
  eta_decay: 1.

lr_scheduler:
  lr_lambda:
    warmup_steps: 25
    max_steps: 200

loss_fn:
  _target_: predictive_cbfs.losses.CheckLoss
  alpha: 0.5

#loss_fn:
#  _target_: torch.nn.MSELoss  # predictive_cbfs.losses.SquaredLoss

eval_function:
  _target_: predictive_cbfs.eval_functions.evaluate_single_double_easy
  _partial_: True