defaults:
  - default_hopper
  - _self_

experiment_name: "hopper_single_int"

epochs: 40
train_epochs: 1
learning_iters: 100
p_cbf_horizon_s: 2
delta_K: 0.25
decorr_prop: 0.2
batch_size: 2048
steps_per_model_checkpoint: 100
save_eval_data: True
save_training_data: False

adjust_distribution: True
converged_tol: 0.05
max_converged_proportion: 0.05

use_barrier: True
JPi_f_inds: [7, 8]

controller:
  _target_: predictive_cbfs.controllers.HopperVelTracking
  t_prop: 0.3
#  keep_inds: null
  keep_inds: [0, 1, 8, 9]  # Only double integrator state
#  keep_inds: [ 0, 1, 2, 8, 9, 10 ]  # Double integerator and z
  raibert_heuristic:
    _target_: predictive_cbfs.controllers.RaibertHeuristic
    K_p: -0.2
    K_v: -0.4
    K_ff: 0.2
    clip_pos: 0.5
    clip_vel: 1.
    clip_vel_des: 0.3
    clip_ang: 0.6
#    randomize_rp: 0.001
    randomize_rp: -0.
    num_robots: ${env_config.env.num_envs}
  robustified_cbf:
    _target_: predictive_cbfs.controllers.RobustifiedCBF
    cbf:
      _target_: predictive_cbfs.cbfs.ObstacleCBF
      alpha: 5
      epsilon: 0
      rs: [ 0.375, 0.375, 0.375, 0.375]
      cxs: [ -0.1, -0.1, 0.75, 1.7 ]
      cys: [ -0.5, 0.5, -0.1, 0.4]
    nom_controller:
      _target_: predictive_cbfs.controllers.SingleIntPosTracking
      k: 1
      zd: [ 0, 0 ]
      v_max: 0.3
    delta:
      _target_: deep_tube_learning.models.MLP
      input_size: 20  # All states
#      input_size: 4  # Only double int states
#      input_size: 6  # CoM states
      output_dim: 1
      num_units: 128
      num_layers: 2
      activation:
        _target_: torch.nn.ReLU
    dyn:
      _target_: predictive_cbfs.roms.SingleInt2D
      dt: 0.01
    delta_max: 5

lr_scheduler:
  lr_lambda:
    warmup_steps: 200
    max_steps: 2000

eta_schedule:
  _target_: predictive_cbfs.utils.eta_schedule
  _partial_: True
  eta_max: ${delta_K}
  eta_decay: 1.0

loss_fn:
  _target_: predictive_cbfs.losses.CheckLoss
  alpha: 0.5

eval_function:
  _target_: predictive_cbfs.eval_functions.evaluate_single_double
  _partial_: True

env_config:
  env:
    num_envs: 4096
    episode_length_s: 3
  control:
    stiffness:
      foot_slide: 900
#      wheel1_rotation: 15.0
#      wheel2_rotation: 15.0
#      wheel3_rotation: 15.0
      wheel1_rotation: 90.0
      wheel2_rotation: 90.0
      wheel3_rotation: 90.0
    damping:
      foot_slide: 60
#      wheel1_rotation: 3.0
#      wheel2_rotation: 3.0
#      wheel3_rotation: 3.0
      wheel1_rotation: 6.0
      wheel2_rotation: 6.0
      wheel3_rotation: 6.0
    wheel_spindown:
      wheel1_rotation: 0.1
      wheel2_rotation: 0.1
      wheel3_rotation: 0.1
    foot_pos_des: 0.021
    action_scale: 1
    decimation: 4
    control_type: "orientation_spindown"
    zero_action: [ 1.0, 0.0, 0.0, 0.0 ]
  domain_rand:
    randomize_friction: False
    friction_range: [ 0.9, 1.1 ]
    randomize_base_mass: False
    added_mass_range: [ -0.5, 0.5 ]
    randomize_inv_base_mass: False
    inv_mass_range: [ -0.5, 0.5 ]
    push_robots: False
    max_push_vel: [ 0.01, 0.01, 0.01, 0.01, 0.01, 0.01 ]  # [vx, vy, vz, wx, wy, wz]
    time_between_pushes: [ 2., 5. ] # min max time (sec) between pushes of the robot. randomly selected in this range
    randomize_rom_distance: False
    max_rom_distance: [ 0.5, 0.5 ]
    zero_rom_distance_likelihood: 0.25
    randomize_com: True
    max_rnd_com_dist: 0.002
    rigid_shape_properties:
      randomize_restitution: False
      restitution_range: [ 0.9, 1.0 ]
      randomize_compliance: False
      compliance_range: [ 0.9, 1.0 ]
      randomize_thickness: False
      thickness_range: [ 0.0, 0.05 ]
    dof_properties:
      randomize_stiffness: False
      randomize_damping: False
      added_damping_range: [ -0.2, 0.2 ]
    spring_properties:
      randomize_stiffness: False
      stiffness_range: [ 0.9, 1.1 ]  # multiplicative
      randomize_damping: False
      damping_range: [ 0.9, 1.1 ]  # multiplicative
      randomize_setpoint: False
      setpoint_range: [ 0.9, 1.1 ]  # multiplicative
    pd_gain_properties:
      randomize_p_gain: False
      p_gain_range: [ 0.95, 1.05 ]  # multiplicative
      randomize_d_gain: False
      d_gain_range: [ 0.95, 1.05 ]  # multiplicative
    torque_speed_properties:
      randomize_max_torque: False
      max_torque_range: [ 0.9, 1.1 ]  # multiplicative
      randomize_max_speed: False
      max_speed_range: [ 0.9, 1.1 ]  # multiplicative
      randomize_slope: False
      slope_range: [ 0.9, 1.1 ]  # multiplicative
  init_state:
    default_dof_pos_noise_lower: [ -0., -0., -0., -0. ]  # [foot, wheel1, 2, 3]
    default_dof_pos_noise_upper: [ 0., 0., 0., 0. ]
    default_dof_vel_noise_lower: [ -0., -0., -0., -0. ]
    default_dof_vel_noise_upper: [ 0., 0., 0., 0. ]
    default_root_pos_noise_lower: [ -0.75, -1.25, -0.0, -0.0, -0.0, -0.0, -0.0 ]  # [x, y, z, qx, qy, qz, qw]
    default_root_pos_noise_upper: [ 2.25, 1.25, 0.0, 0.0, 0.0, 0.0, 0.0 ]
    default_root_vel_noise_lower: [ -0.3, -0.3, -0.0, -0.0, -0.0, -0.0 ]  # [vx, vy, vz, wx, wy, wz]
    default_root_vel_noise_upper: [ 0.3, 0.3, 0.0, 0.0, 0.0, 0.0 ]
  noise:
    add_noise: False
    noise_level: 1.0
    noise_scales:
      dof_vel: 1.5
      lin_vel: 0.001
      ang_vel: 0.005
      gravity: 0.005
      z_pos: 0.002
      quat: 0.002