seed: 42
dataset_name: "dataset"

num_robots: 1000
epochs: 10
task: "anymal_c_flat"
headless: True
save_debugging_data: False
upload_to_wandb: True

track_yaw: True

acc_max: 2
acc_min: -2
alpha_max: 4
alpha_min: -4
vel_max: 1
vel_min: -1
vel_par_max: 1
vel_perp_max: 0.5
vel_par_min: -0.5
vel_perp_min: -0.5
omega_max: 1
omega_min: -1
pos_max: 1e9
pos_min: -1e9

reduced_order_model:
  _target_: trajopt.rom_dynamics.Unicycle
  dt: 0.02
  z_min:
    _target_: numpy.array
    object:
      - ${pos_min}
      - ${pos_min}
      - ${pos_min}
  z_max:
    _target_: numpy.array
    object:
      - ${pos_max}
      - ${pos_max}
      - ${pos_max}
  v_min:
    _target_: numpy.array
    object:
      - ${vel_par_min}
      - ${omega_min}
  v_max:
    _target_: numpy.array
    object:
      - ${vel_par_max}
      - ${omega_max}
  n_robots: ${num_robots}
  backend: "numpy"
  seed: ${seed}

Kp:
  _target_: numpy.diag
  v: [2, 2, 2]

u_vel_max: 1.5
u_vel_min: -1.5
u_vel_par_max: 1.5
u_vel_perp_max: 0.75
u_vel_par_min: -0.75
u_omega_max: 1.5
u_omega_min: -1.5
u_min:
  _target_: numpy.array
  object:
    - ${u_vel_min}
    - ${u_vel_min}
    - ${u_omega_min}
u_max:
  _target_: numpy.array
  object:
    - ${u_vel_max}
    - ${u_vel_max}
    - ${u_omega_max}


sample_hold_dt:
  _target_: deep_tube_learning.utils.UniformSampleHoldDT
  t_low: 1
  t_high: 100
  n_robots: ${num_robots}


