seed: 42
dataset_name: "dataset"

num_robots: 2
epochs: 10
task: "hopper_flat_trajectory"
headless: False
save_debugging_data: False
upload_to_wandb: False

track_yaw: True

acc_max: 2
acc_min: -2
alpha_max: 4
alpha_min: -4
vel_max: .35
vel_min: -.35
vel_par_max: 1
vel_perp_max: 0.5
vel_par_min: -0.5
vel_perp_min: -0.5
omega_max: 1
omega_min: -1
pos_max: 1e9
pos_min: -1e9

reduced_order_model:
  _target_: trajopt.rom_dynamics.SingleInt2D
  dt: 0.02
  z_min:
    _target_: numpy.array
    object:
      - ${pos_min}
      - ${pos_min}
      - ${pos_min}
  z_max:
    _target_: numpy.array
    object:
      - ${pos_max}
      - ${pos_max}
      - ${pos_max}
  v_min:
    _target_: numpy.array
    object:
      - ${vel_par_min}
      - ${omega_min}
  v_max:
    _target_: numpy.array
    object:
      - ${vel_par_max}
      - ${omega_max}
  n_robots: ${num_robots}
  backend: "numpy"

trajectory_generator:
  _target_: trajopt.rom_dynamics.TrajectoryGenerator
  _partial_: True
  t_sampler:
    _target_: deep_tube_learning.utils.UniformSampleHoldDT
    t_low: 1
    t_high: 2
  freq_low: 0.01
  freq_high: 2
  weight_sampler:
    _target_: deep_tube_learning.utils.WeightSamplerSampleAndHold
  seed: ${seed}
  N: 10
