seed: 0

wandb_experiment: null
dataset_name: "hopper_trajectory"

epochs: 10
headless: False
save_debugging_data: False
upload_to_wandb: False
track_yaw: False

acc_max: 1.5
acc_min: -1.5
alpha_max: 2
alpha_min: -2
vel_max: 0.3
vel_min: -0.3
vel_par_max: 0.3
vel_perp_max: 0.15
vel_par_min: -0.15
vel_perp_min: -0.15
omega_max: 0.4
omega_min: -0.4
pos_max: 1e9
pos_min: -1e9

env_config:
  env:
    num_envs: 4096
#  terrain:
#    curriculum: False
  noise:
    add_noise: False
  domain_rand:
    push_robots: False
    randomize_friction: False
    randomize_base_mass: False
    randomize_inv_base_mass: False
    rigid_shape_properties:
      randomize_stiffness: False
      randomize_damping: False

