seed: 42
dataset_name: "debugging_dataset_collection"

num_robots: 2
epochs: 1000
task: "anymal_c_flat"

track_yaw: False

acc_max: 2
acc_min: -2
alpha_max: 4
vel_max: 1
vel_min: -1
vel_par_max: 1
vel_perp_max: 0.5
vel_par_min: -0.5
omega_max: 1
omega_min: -1
pos_max: numpy.inf
pos_min: -numpy.inf

reduced_order_model:
  _target_: trajopt.rom_dynamics.SingleInt2D
  dt: 0.02
  z_min:
    _target_: numpy.array
    object:
      - ${pos_min}
      - ${pos_min}
  z_max:
    _target_: numpy.array
    object:
      - ${pos_max}
      - ${pos_max}
  v_min:
    _target_: numpy.array
    object:
      - ${vel_min}
      - ${vel_min}
  v_max:
    _target_: numpy.array
    object:
      - ${vel_max}
      - ${vel_max}
  backend: "numpy"

Kp: 2
u_vel_max: 1
u_vel_min: -1
u_vel_par_max: 1
u_vel_perp_max: 0.5
u_vel_par_min: -0.5
u_omega_max: 1
u_omega_min: -1
u_min:
  _target_: numpy.array
  object:
    - ${u_vel_min}
    - ${u_vel_min}
    - ${u_omega_min}
u_max:
  _target_: numpy.array
  object:
    - ${u_vel_max}
    - ${u_vel_max}
    - ${u_omega_max}


sample_hold_dt:
  _target_: deep_tube_learning.utils.UniformSampleHoldDT
  t_low: 1
  t_high: 100


