defaults:
  - default_custom
  - _self_

seed: 0

dataset_name: "double_single_int"

epochs: 25
headless: True
save_debugging_data: False
upload_to_wandb: False
track_yaw: False
curriculum: 0

acc_max: 0.5
acc_min: -0.5
vel_max: 0.3
vel_min: -0.3
vel_max_rom: 0.2
vel_min_rom: -0.2

controller:
  _target_: deep_tube_learning.controllers.DoubleSingleTracking
  _partial_: True
  Kp: 10
  Kd: 10

env_config:
  env:
    num_envs: 8192
    episode_length_s: 20
    model:
      dt: 0.05
      cls: 'DoubleInt2D'
      z_min:
        - ${pos_min}
        - ${pos_min}
        - ${vel_min}
        - ${vel_min}
      z_max:
        - ${pos_max}
        - ${pos_max}
        - ${vel_max}
        - ${vel_max}
      v_min:
        - ${acc_min}
        - ${acc_min}
      v_max:
        - ${acc_max}
        - ${acc_max}
  rom:
    cls: 'SingleInt2D'
    dt: 0.1
    z_min:
      - ${pos_min}
      - ${pos_min}
    z_max:
      - ${pos_max}
      - ${pos_max}
    v_min:
      - ${vel_min_rom}
      - ${vel_min_rom}
    v_max:
      - ${vel_max_rom}
      - ${vel_max_rom}
  trajectory_generator:
    cls: 'TrajectoryGenerator'
    t_samp_cls: 'UniformSampleHoldDT'
    weight_samp_cls: 'UniformWeightSamplerNoRamp'
    N: 10
    t_low: 1
    t_high: 2
    freq_low: 0.01
    freq_high: 2
    seed: ${seed}
    prob_stationary: 0.0005
    dN: 1
  noise:
    add_noise: False
  domain_rand:
    randomize_rom_distance: True
    max_rom_distance: [1.0, 1.0]
    zero_rom_dist_llh: 0.25
  init_state:
    default_noise_lower: [0.0, 0.0, -0.1, -0.1]
    default_noise_upper: [0.0, 0.0, 0.1, 0.1]
