defaults:
  - default
  - _self_

dataset_name: "double_integrator"

num_robots: 11
epochs: 2
save_debugging_data: True
upload_to_wandb: False

track_yaw: False
Kp:
  _target_: numpy.diag
  v: [10, 10, 10]

reduced_order_model:
  _target_: reftraj.rom_dynamics.DoubleInt2D
  z_min:
    _target_: numpy.array
    object:
      - ${pos_min}
      - ${pos_min}
      - ${vel_min}
      - ${vel_min}
  z_max:
    _target_: numpy.array
    object:
      - ${pos_max}
      - ${pos_max}
      - ${vel_max}
      - ${vel_max}
  v_min:
    _target_: numpy.array
    object:
      - ${acc_min}
      - ${acc_min}
  v_max:
    _target_: numpy.array
    object:
      - ${acc_max}
      - ${acc_max}