defaults:
  - default
  - _self_

dataset_name: "extended_lateral_unicycle"

num_robots: 11
epochs: 2
save_debugging_data: True
upload_to_wandb: False

reduced_order_model:
  _target_: trajopt.rom_dynamics.ExtendedLateralUnicycle
  z_min:
    _target_: numpy.array
    object:
      - ${pos_min}
      - ${pos_min}
      - ${pos_min}
      - ${vel_par_min}
      - ${vel_perp_min}
      - ${omega_min}
  z_max:
    _target_: numpy.array
    object:
      - ${pos_max}
      - ${pos_max}
      - ${pos_max}
      - ${vel_par_max}
      - ${vel_perp_max}
      - ${omega_max}
  v_min:
    _target_: numpy.array
    object:
      - ${acc_min}
      - ${acc_min}
      - ${alpha_min}
  v_max:
    _target_: numpy.array
    object:
      - ${acc_max}
      - ${acc_max}
      - ${alpha_min}