defaults:
  - default
  - _self_

dataset_name: "extended_unicycle"

num_robots: 11
epochs: 2
save_debugging_data: True
upload_to_wandb: False

Kp:
  _target_: numpy.diag
  v: [5, 5, 2]

reduced_order_model:
  _target_: reftraj.rom_dynamics.ExtendedUnicycle
  z_min:
    _target_: numpy.array
    object:
      - ${pos_min}
      - ${pos_min}
      - ${pos_min}
      - ${vel_par_min}
      - ${omega_min}
  z_max:
    _target_: numpy.array
    object:
      - ${pos_max}
      - ${pos_max}
      - ${pos_max}
      - ${vel_par_max}
      - ${omega_max}
  v_min:
    _target_: numpy.array
    object:
      - ${acc_min}
      - ${alpha_min}
  v_max:
    _target_: numpy.array
    object:
      - ${acc_max}
      - ${alpha_max}