defaults:
  - default_hopper_trajectory
  - _self_

epochs: 10

dataset_name: "hopper_trajectory_single_int"
wandb_experiment: "coleonguard-Georgia Institute of Technology/RL_Training/fcoard3m"
curriculum: 7
upload_to_wandb: True

vel_min: -0.05
vel_max: 0.05

controller:
  type: 'rh'
  # Below for option 'rh'
  config_name: "hopper_trajectory_single_int.yaml"
  K_p: -0.1
  K_v: -0.3
  K_ff: 0.0
  clip_value_pos: 0.4
  clip_value_vel: 1.
  clip_value_total: 0.2
  N: 8

env_config:
  env:
    num_envs: 8192
    episode_length_s: 20
  rom:
    dt: 0.1
    cls: 'SingleInt2D'
    z_min:
      - ${pos_min}
      - ${pos_min}
    z_max:
      - ${pos_max}
      - ${pos_max}
    v_min:
      - ${vel_min}
      - ${vel_min}
    v_max:
      - ${vel_max}
      - ${vel_max}
  trajectory_generator:
    t_low: 1
    t_high: 5
    freq_low: 0.5
    freq_high: 3
    seed: ${seed}
    N: 50
    dN: 1