defaults:
  - default_hopper_velocity
  - _self_

wandb_experiment: "coleonguard-Georgia Institute of Technology/RL_Training/0w94yf4r"
dataset_name: "hopper_velocity_single_int"

epochs: 10
save_debugging_data: True
upload_to_wandb: False

track_yaw: False
Kp:
  _target_: numpy.diag
  v: [5, 5, 5]

reduced_order_model:
  _target_: trajopt.rom_dynamics.SingleInt2D
  _partial_: True
  z_min:
    _target_: numpy.array
    object:
      - ${pos_min}
      - ${pos_min}
  z_max:
    _target_: numpy.array
    object:
      - ${pos_max}
      - ${pos_max}
  v_min:
    _target_: numpy.array
    object:
      - ${vel_min}
      - ${vel_min}
  v_max:
    _target_: numpy.array
    object:
      - ${vel_max}
      - ${vel_max}
  backend: 'numpy'
  n_robots: ${env_config.env.num_envs}
