defaults:
  - default_hopper_trajectory
  - _self_

curriculum: 7
dataset_name: "hopper_trajectory_single_int"
wandb_experiment: "coleonguard-Georgia Institute of Technology/RL_Training/fcoard3m"

vel_min: -0.2
vel_max: 0.2

controller:
  type: 'rh'
  # Below for option 'rh'
  config_name: "hopper_trajectory_single_int.yaml"
  K_p: -0.1
  K_v: -0.3
  K_ff: 0.0
  clip_value_pos: 0.5
  clip_value_vel: 1.
  clip_value_total: 0.2

env_config:
  rom:
    cls: 'SingleInt2D'
    z_min:
      - ${pos_min}
      - ${pos_min}
    z_max:
      - ${pos_max}
      - ${pos_max}
    v_min:
      - ${vel_min}
      - ${vel_min}
    v_max:
      - ${vel_max}
      - ${vel_max}
  trajectory_generator:
    t_low: 1
    t_high: 5
    freq_low: 0.01
    freq_high: 1
    seed: ${seed}