defaults:
  - default_hopper
  - _self_

epochs: 50

dataset_name: "hopper_single_int"
wandb_experiment: "coleonguard-Georgia Institute of Technology/RL_Training/fcoard3m"
curriculum: 7
upload_to_wandb: True

vel_max: 0.2
vel_min: -0.2

controller:
  type: 'rh'
  # Below for option 'rh'
  config_name: "hopper_single_int.yaml"
  K_p: -0.15
  K_v: -0.4
  K_ff: 0.1
  clip_pos: 0.5
  clip_vel: 1.
  clip_vel_des: 0.2
  clip_ang: 0.2
  N: 1

env_config:
  env:
    num_envs: 8192
    episode_length_s: 80
  rom:
    dt: 0.4
    cls: 'SingleInt2D'
    z_min:
      - ${pos_min}
      - ${pos_min}
    z_max:
      - ${pos_max}
      - ${pos_max}
    v_min:
      - ${vel_min}
      - ${vel_min}
    v_max:
      - ${vel_max}
      - ${vel_max}
  trajectory_generator:
    cls: 'TrajectoryGeneratorH2H'
    t_samp_cls: 'UniformSampleHoldDT'
    weight_samp_cls: 'UniformWeightSampler'
    N: 10
    t_low: 2
    t_high: 10
    freq_low: 0.01
    freq_high: 2
    seed: ${seed}
    prob_stationary: 0.01
    dN: 1
    prob_rnd: 0.05
    noise_max_std: 0.05
    noise_llh: 0.25