defaults:
  - default_hopper
  - _self_

epochs: 50

dataset_name: "hopper_single_int"
wandb_experiment: "coleonguard-Georgia Institute of Technology/RL_Training/fcoard3m"
curriculum: 7
upload_to_wandb: True

vel_max: 0.2
vel_min: -0.2

controller:
  type: 'rh'
  # Below for option 'rh'
  config_name: "hopper_single_int.yaml"
  K_p: -0.2
  K_v: -0.4
  K_ff: 0.2
  clip_pos: 0.5
  clip_vel: 1.
  clip_vel_des: 0.2
  clip_ang: 0.4
  N: 1

env_config:
  env:
    num_envs: 8192
    episode_length_s: 20
  rom:
    dt: 0.1
    cls: 'SingleInt2D'
    z_min:
      - ${pos_min}
      - ${pos_min}
    z_max:
      - ${pos_max}
      - ${pos_max}
    v_min:
      - ${vel_min}
      - ${vel_min}
    v_max:
      - ${vel_max}
      - ${vel_max}
  trajectory_generator:
    cls: 'TrajectoryGenerator'
    t_samp_cls: 'UniformSampleHoldDT'
    weight_samp_cls: 'UniformWeightSamplerBiasRampExtremeExp'
    N: 10
    t_low: 0.5
    t_high: 5
    freq_low: 0.1
    freq_high: 3
    seed: ${seed}
    prob_stationary: 0.05
    dN: 1
    prob_rnd: 0.05
    noise_max_std: 0.1
    noise_llh: 0.25
  control:
    stiffness:
      foot_slide: 900
#      wheel1_rotation: 15.0
#      wheel2_rotation: 15.0
#      wheel3_rotation: 15.0
      wheel1_rotation: 90.0
      wheel2_rotation: 90.0
      wheel3_rotation: 90.0
    damping:
      foot_slide: 60
#      wheel1_rotation: 3.0
#      wheel2_rotation: 3.0
#      wheel3_rotation: 3.0
      wheel1_rotation: 6.0
      wheel2_rotation: 6.0
      wheel3_rotation: 6.0
    wheel_spindown:
      wheel1_rotation: 0.1
      wheel2_rotation: 0.1
      wheel3_rotation: 0.1
    foot_pos_des: 0.021
    action_scale: 1
    decimation: 4
    control_type: "orientation_spindown"
    zero_action: [ 1.0, 0.0, 0.0, 0.0 ]
  domain_rand:
    randomize_friction: False
    friction_range: [ 0.9, 1.1 ]
    randomize_base_mass: False
    added_mass_range: [ -0.5, 0.5 ]
    randomize_inv_base_mass: False
    inv_mass_range: [ -0.5, 0.5 ]
    push_robots: True
    max_push_vel: [ 0.01, 0.01, 0.01, 0.05, 0.05, 0.05 ]  # [vx, vy, vz, wx, wy, wz]
    time_between_pushes: [ 1., 5. ] # min max time (sec) between pushes of the robot. randomly selected in this range
    randomize_rom_distance: True
    max_rom_distance: [ 1., 1. ]
    zero_rom_distance_likelihood: 0.25
    rigid_shape_properties:
      randomize_restitution: False
      restitution_range: [ 0.9, 1.0 ]
      randomize_compliance: False
      compliance_range: [ 0.9, 1.0 ]
      randomize_thickness: False
      thickness_range: [ 0.0, 0.05 ]
    dof_properties:
      randomize_stiffness: False
      randomize_damping: False
      added_damping_range: [ -0.2, 0.2 ]
    spring_properties:
      randomize_stiffness: True
      stiffness_range: [ 0.9, 1.1 ]  # multiplicative
      randomize_damping: True
      damping_range: [ 0.9, 1.1 ]  # multiplicative
      randomize_setpoint: True
      setpoint_range: [ 0.9, 1.1 ]  # multiplicative
    pd_gain_properties:
      randomize_p_gain: False
      p_gain_range: [ 0.9, 1.1 ]  # multiplicative
      randomize_d_gain: False
      d_gain_range: [ 0.9, 1.1 ]  # multiplicative
    torque_speed_properties:
      randomize_max_torque: False
      max_torque_range: [ 0.95, 1.05 ]  # multiplicative
      randomize_max_speed: False
      max_speed_range: [ 0.9, 1.1 ]  # multiplicative
      randomize_slope: False
      slope_range: [ 0.9, 1.1 ]  # multiplicative
  init_state:
    default_dof_pos_noise_lower: [ -0., -0., -0., -0. ]  # [foot, wheel1, 2, 3]
    default_dof_pos_noise_upper: [ 0., 0., 0., 0. ]
    default_dof_vel_noise_lower: [ -0., -0., -0., -0. ]
    default_dof_vel_noise_upper: [ 0., 0., 0., 0. ]
    default_root_pos_noise_lower: [ -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0 ]  # [x, y, z, qx, qy, qz, qw]
    default_root_pos_noise_upper: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]
    default_root_vel_noise_lower: [ -0.0, -0.0, -0.0, -0.0, -0.0, -0.0 ]  # [vx, vy, vz, wx, wy, wz]
    default_root_vel_noise_upper: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]
  curriculum:
    use_curriculum: False
  noise:
    add_noise: False
    noise_level: 1.0
    noise_scales:
      dof_vel: 1.5
      lin_vel: 0.001
      ang_vel: 0.005
      gravity: 0.005
      z_pos: 0.002
      quat: 0.002